# Generated by Django 4.0.4 on 2022-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('parution', models.DateField(blank=True)),
                ('realisateur', models.CharField(max_length=30)),
                ('resume', models.TextField(blank=True)),
            ],
        ),
    ]
